### ISSUE TITLE
save history to file

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1032]
Original [issue 1032](https://code.google.com/p/sqlyog/issues/detail?id=1032) created by webyog on 2009-03-24T09:02:27.000Z:

And old request is that hsitory (what is now stored in memory) should 
(oprtionally or not) be stored or 'spooled' to a file so that history from 
a previous session was available from a new session.  It could also be 
used for auditing purposes.

**Comment by abhishekpwy** [comment]
It is implemented. Closing this ticket.
