### ISSUE TITLE
Multi-file Selector Dialogs, Allow selection of multiple files in any dialog 

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1180]
Original [issue 1180](https://code.google.com/p/sqlyog/issues/detail?id=1180) created by webyog on 2009-10-15T05:40:29.000Z:

Users says,
&quot;I'd like to be able to select multiple files in file selector dialogs like
the Open file ones (same tab or new one). In the Open File in Same Tab
case, the &quot;same tab&quot; part would only apply to one of the files selected.&quot;

For more info,
http://www.webyog.com/forums//index.php?showtopic=4883

**Comment by sibwy** [comment]
Another user has asked for selecting and opening multiple files from the File explorer dialog, here >> http://forums.webyog.com/index.php?showtopic=7956
