### ISSUE TITLE
GUI transactions support

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1526]
Original [issue 1526](https://code.google.com/p/sqlyog/issues/detail?id=1526) created by webyog on 2010-10-23T18:38:15.000Z:

We will soon need to consider an GUI option for start_transaction/set autocommit = 0, commit and rollback. (icons, shortcuts and 'red alerts' in the interface like 'transaction not yet committed'.

Reasons:
* Several GUI tools (incl. WB) has. 
* With MySQL 5.5 InnoDB is default engine
* Starting server with --autocommit = 0 seems to be not uncommon now ('oracle style')

**Comment by peterwy** [comment]
+ http://forums.webyog.com/index.php?showtopic=7908

**Comment by reguillemette** [comment]
Is it something we could expect in the next months / releases ?
This issue is 5 years old. Most of the client used with Oracle DB (Toad, SQL dev, etc) are not commiting automatically.
I also found SQLyog a bit unsafe to work because of this.

**Comment by sibwy** [comment]
This feature has been added in SQLyog 12.3.0 release. The release notes can be referred from the blog >> https://blog.webyog.com/introducing-gui-transaction-support-in-sqlyog-12-3-0/
