### ISSUE TITLE
4 byte utf8 problem

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1536]
Original [issue 1536](https://code.google.com/p/sqlyog/issues/detail?id=1536) created by webyog on 2010-10-25T10:55:10.000Z:

This is a 'hypothesis' only that should be tested!

SQLyog is compiled with a 5.0/5.1 MySQL API.  I am afraid that we fail to handle 4-byte utf8/utf16/utf32 data from a MySQL 5.5 server.

**Comment by peterwy** [comment]
Closing this. Research should start from scratch.
