### ISSUE TITLE
MySQL 5.5 supports index comments

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1548]
Original [issue 1548](https://code.google.com/p/sqlyog/issues/detail?id=1548) created by webyog on 2010-10-29T16:55:24.000Z:

refer http://dev.mysql.com/doc/refman/5.5/en/create-table.html

index_type:
    USING {BTREE | HASH}

index_option:
    KEY_BLOCK_SIZE [=] value
  | index_type
  | WITH PARSER parser_name
  | COMMENT 'string'

.. should probably be considered in the context of #&nbsp;1534

**Comment by sibwy** [comment]
This feature has been added in SQLyog 12.3.0 release. The release notes can be referred from the blog >> https://blog.webyog.com/introducing-gui-transaction-support-in-sqlyog-12-3-0/
