### ISSUE TITLE
Request that Object Browser window has constant width

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1680]
Original [issue 1680](https://code.google.com/p/sqlyog/issues/detail?id=1680) created by webyog on 2011-07-28T14:10:37.000Z:

http://www.webyog.com/forums/index.php?showtopic=6189

&quot;The width of the left hand frame (where all of the databases are listed) annoyingly changes its width when the SqlYog application is made wider or narrower. There is no good reason for the left frame to behave in this manner. Its width should be either precisely what I have set it to, or sized to just fit the content there.&quot;

**Comment by sibwy** [comment]
Fixed in v13.1.2
