### ISSUE TITLE
how to download linux edition in ubuntu 11.04

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1683]
Original [issue 1683](https://code.google.com/p/sqlyog/issues/detail?id=1683) created by webyog on 2011-08-09T05:33:20.000Z:

<b>What steps will reproduce the problem?</b>
1.i download sja92
2.i extract the folder
3.i click in sja 

<b>What is the expected output? What do you see instead?</b>
nothing at all

<b>What version of the product are you using? On what operating system?</b>
9.20 and 9.1 and 8.882 linux edition on ubuntu 11.04

<b>Please provide any additional information below.</b>

**Comment by eliseuchmod777** [comment]
instalei ele com wine mas não conecta no MariaDB.
