### ISSUE TITLE
the 'Scheduler and Reporting tool' should deliver results more flexible ways

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1696]
Original [issue 1696](https://code.google.com/p/sqlyog/issues/detail?id=1696) created by webyog on 2011-08-23T06:52:20.000Z:

From IB #&nbsp;29940: &quot;.. we need to have our query results attached by email in an Excel format as our results will rarely be below 1000 rows.&quot;

Such file should be a CSV file then I think.

**Comment by sibwy** [comment]
Another user has asked for scheduling a job for exporting the data into csv file then send via email. The user request can be found in HS >> # 281407

**Comment by sibwy** [comment]
Another user has asked for this feature of attaching the query results in CSV format in the email. The user request can be found in HS #285385

**Comment by peterwy** [comment]
See also https://secure.helpscout.net/conversation/445645144/292977/

**Comment by sibwy** [comment]
Another request from a user in HS >> #293705

**Comment by sibwy** [comment]
The option to include the results of the query in a CSV attachment is implemented in v13.0. Refer the release notes, [here](http://blog.sqlyog.com/sqlyog-mysql-gui-13-0-released/)
