### ISSUE TITLE
REGEXP in object browser filter.

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1895]
Original [issue 1895](https://code.google.com/p/sqlyog/issues/detail?id=1895) created by webyog on 2012-12-27T04:56:18.000Z:

User requested for REGEXP in Object browser filter. 

Refer forum post: http://forums.webyog.com/index.php?showtopic=6916

**Comment by sibwy** [comment]
There is another user who has asked for the same feature. The user request can be found in HS >> 250956

**Comment by wyaadarsh** [comment]
Implemented in SQLyog 12.4.3.
