### ISSUE TITLE
Contents Not Shown Fully in BLOB-viewer 

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1933]
Original [issue 1933](https://code.google.com/p/sqlyog/issues/detail?id=1933) created by webyog on 2013-04-26T10:35:39.000Z:

when showing the result of a query sqlyog does not always display the full column contents without marking the text. The scroll bar is at the very end, although there is more content to show. Only by marking the text it is shown in full.

Refer: http://forums.webyog.com/index.php?showtopic=7121

**Comment by sibwy** [comment]
This issue has been fixed in the SQLyog 11.26 version. Please refer >> http://blog.webyog.com/2013/10/11/sqlyog-mysql-gui-11-26-released/
