### ISSUE TITLE
 Tool-tip on column header

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#1988]
Original [issue 1988](https://code.google.com/p/sqlyog/issues/detail?id=1988) created by webyog on 2013-12-04T11:35:04.000Z:

User requested for tooltip on column header.

Refer: http://forums.webyog.com/index.php?showtopic=7346

**Comment by sibwy** [comment]
Another user has asked for a feature to include a tooltip that would display the full column name and could also display the datatype on hovering over the abbreviated column title in the ’Table Data’ tab of the ‘Result Window’.

The request can be found in HS >> 237226809/189269

**Comment by sibwy** [comment]
This feature has been added in SQLyog 12.3.0 release. The release notes can be referred from the blog >> https://blog.webyog.com/introducing-gui-transaction-support-in-sqlyog-12-3-0/
