### ISSUE TITLE
Issue with multiline strings in text mode

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#2071]
Original [issue 2072](https://code.google.com/p/sqlyog/issues/detail?id=2072) created by webyog on 2015-01-02T19:27:05.000Z:

Execute

SELECT '
this 
is 
one'
 AS `one`,
'
this 
is 
two'
AS `two`;

See pics for grid- and text mode. In text mode `one` is displayed as  'whitespace'.

**Comment by sibwy** [comment]
This issue has been fixed in SQLyog 12.2.3. 

You can refer the release notes, here >> http://blog.webyog.com/2016/05/26/sqlyog-mysql-gui-12-2-3-released/
