### ISSUE TITLE
Request: Filter/search Function For Connections

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#2073]
Original [issue 2074](https://code.google.com/p/sqlyog/issues/detail?id=2074) created by webyog on 2015-01-12T10:27:06.000Z:

Refer-http://forums.webyog.com/index.php?showtopic=7613&amp;hl=

User says-&quot;as we have multiple (&gt; 50) connections it would be very handy, if you implement the possibility to filter the connection combobox by a string.
Please see the attachment as an example.
By Typing a text like &quot;abc&quot; in the filter field the Stored Connection Combobox should be reduced by Connections which names contain the phrase &quot;abc&quot;.&quot;

**Comment by Kartikwy** [comment]
Another request. Refer- https://secure.helpscout.net/conversation/95365731/110636/

**Comment by Kartikwy** [comment]
The idea is to make the search for connections in the connection name list simpler.Another similar request.. 
https://secure.helpscout.net/conversation/103440782/115439/

Here the user wants the similar kind of connections to be grouped.

**Comment by Kartikwy** [comment]
fixed in 12.15.. http://blog.webyog.com/2015/10/07/sqlyog-mysql-gui-12-15-released/
