### ISSUE TITLE
Editing a trigger CORRUPTS the quotes !

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#2074]
Original [issue 2075](https://code.google.com/p/sqlyog/issues/detail?id=2075) created by webyog on 2015-01-27T16:06:01.000Z:

<b>What steps will reproduce the problem?</b>
1. Create a trigger
CREATE
    TRIGGER `test_trigger` BEFORE DELETE ON `test_table` 
    FOR EACH ROW BEGIN
	DECLARE a VARCHAR(25);
	SET a = CONCAT('I''m not happy');
    END;
$$
2. close the trigger's editor tab
3. refresh the trigger list in your database on the left
4. right click your trigger &gt; Alter. Here is the corrupted line
SET a = CONCAT('I'm not happy');

What is the expected output?
SET a = CONCAT('I''m not happy');

What do you see instead?
SET a = CONCAT('I'm not happy');

<b>What version of the product are you using? On what operating system?</b>
Community v12.04 64 bit on Windows Server 2012, MySQL 5.1.5

**Comment by abhishekpwy** [comment]
Fixed in version 12.09.
