### ISSUE TITLE
j

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#2075]
Original [issue 2076](https://code.google.com/p/sqlyog/issues/detail?id=2076) created by webyog on 2015-02-26T08:59:37.000Z:

<b>What steps will reproduce the problem?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>

<b>Please provide any additional information below.</b>

**Comment by abhishekpwy** [comment]
Invalid.
