### ISSUE TITLE
DATA TAB REFRESHING ISSUE

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#2076]
Original [issue 2077](https://code.google.com/p/sqlyog/issues/detail?id=2077) created by webyog on 2015-03-08T16:55:25.000Z:

<b>What steps will reproduce the problem?</b>

1. Once I open query tab and load table data into first query tab. Then I open next   tab and load another table data into it.
2. After I select first tab it automatically loads secondly loaded table data.

This bug not seen in 9.51. But it happened in 11.5

So still I recommended 9.51 is better than 11.5.

Otherwise, please tell me how to fix this???

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>

<b>Please provide any additional information below.</b>

**Comment by abhishekpwy** [comment]
This is not a bug. We have changed the logical structure of SQLyog. Now table data tab is not a child of query tab. You should do select * from <table_name> to get the result in result tab. Result tab is child of query tab and will not be changed on changing selection in OB.

**Comment by vishalwy** [comment]
You can also use Table -> Open in new tab to open the data tab in sticky mode. A data tab opened in sticky mode wont be refreshed when the selection in object browser change.
