### ISSUE TITLE
Invalid JSON  created while exporting data.

### ISSUE THREAD

**Issue by vishu2111** [webyog/sqlyog-community#2083]
I'm using SQLyog Community edition 12.11(64 bit).I have  used exporting feature in it.
Try to export table data as JSON. after exporting data you will see one extra COMMA is appended before RIGHT_SUQARE_BRACKET.
e.g .

[
{ 
"Id":200,
"InputIds":"114",
"OutputIds":"116"
},
]

**Comment by abhishekpwy** [comment]
Comma is before '}' also or only before ']'? ex- "OutputIds":"116",<--comma(',') here?

**Comment by vishu2111** [comment]
The Updated JSON : 

[
{ 
"Id":200,
"InputIds":"114",
"OutputIds":"116"
},
]

**Comment by abhishekpwy** [comment]
It is already reported and fixed in our internal code tree. Fix will be included in next release.
