### ISSUE TITLE
Dropdown list of the tabs where one can view a list of all open files specially when number of tabs opened is large.

### ISSUE THREAD

**Issue by Kartikwy** [webyog/sqlyog-community#2085]
Difficult to use SQLyog when the number of tabs (Connection and Query) is large such that the names fill up the area and the tabs cannot be seen or accessed unless they are scrolled to. 

Here Refer>> https://secure.helpscout.net/conversation/108008976/118023/

**Comment by Kartikwy** [comment]
User has requested that when multiple tabs are opened it will for a multi layer in the bar as shown in the screenshot in the link here>> http://forums.webyog.com/index.php?showtopic=7989.

**Comment by sibwy** [comment]
Another user has asked for a scroll option to move to the tabs on the left/right. The user request can be found in the Forums, [here](https://forums.webyog.com/forums/topic/feature-request-mouse-wheel-on-query-tabs/).

**Comment by sibwy** [comment]
This feature is implemented in v13.1.2
