### ISSUE TITLE
Table Description/Comment - Limitation

### ISSUE THREAD

**Issue by candido1212** [webyog/sqlyog-community#2092]
Hello,
Good morning, I was wanting to put comments in the database tables, but found a limitation of 490 characters, but in another mysql client, I had no problems as far saved more than 490 characters.

this is a limitation of SQLyog or a bug?

version: 12.16 32bits

=== pt-br ===
bom dia, eu estava querendo colocar comentários nas tabelas do banco, porém encontrei uma limitação de 490 caracteres, porém em outro cliente do mysql, não tive problemas, pois salvou muito mais de 490 caracteres.

isso é uma limitação do sqlyog ou um bug?

**Comment by sibwy** [comment]
This issue has been fixed in the 12.2.2 release. Now it is possible to enter upto 2048 characters in the Table-level comments. 

The release notes can be found here >> http://blog.webyog.com/2016/05/05/sqlyog-mysql-gui-12-2-2-released/
