### ISSUE TITLE
SQL in cell is being evaluated

### ISSUE THREAD

**Issue by joereynolds** [webyog/sqlyog-community#2095]
We have a cell in a table called 'sql_snippet' (don't ask me why...just don't), Which contains raw SQL, when I try to update it by clicking on the cell and updating it in the textbox, SQLYog then tries to evaluate the SQL and won't update the cell.

Linux Mint using Wine for Yog.

Screenshots for clarity

![screenshot from 2016-01-22 10 28 43](https://cloud.githubusercontent.com/assets/9536682/12508269/eb7908d4-c0f2-11e5-8641-76800c47330d.png)

![screenshot from 2016-01-22 10 29 55](https://cloud.githubusercontent.com/assets/9536682/12508300/1263bbd8-c0f3-11e5-8611-516533bef673.png)

![screenshot from 2016-01-22 10 30 25](https://cloud.githubusercontent.com/assets/9536682/12508314/249fd534-c0f3-11e5-9edc-5f8ef4af4dcf.png)

My 'solution' at the moment is to just wrap the entire thing in a string but that's not really fixing the core issue

**Comment by peterwy** [comment]
-- I cannot reproduce with a simple test case


CREATE TABLE `pltest`.`sqltest` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bl` BLOB,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8

-- now inserting "1" from GUI and next updating with "2" from GUI generates statements 

--
INSERT INTO `pltest`.`sqltest` (`bl`) VALUES ('select 1'); 
--
UPDATE `pltest`.`sqltest` SET `bl` = 'select 2' WHERE `id` = '1';
-- 

-- and 
SELECT * FROM `pltest`.`sqltest`;
/* returns as expected

    id  bl        
------  ----------
     1  select 2 */



This issue tracker is not a proper place for the discussion taht this will require.  Repors here should be short an concise.

Please use our Forums or mail us at support@webyog.com with a complete reproducible test case. And please also to tell the MySQL server version and the SQLyog version.


And BTW: SQLyog itself never evaluates any SQL.  It is the server that does. The only thing SQLyog does is to send SQL statements to the server.But we may be raming them wrong, of course in some cases

**Comment by joereynolds** [comment]
Not a bug, but rather an option that is on by default

"Hi,

This is happening because here 'IF()' is treated as a function. Disable "smart" KEYWORDS/FUNCTIONS/DEFAULT handling from Tools->Preferences->others and then check. Now, it will not be treated as a function but a normal text. "
