### ISSUE TITLE
SSH and SSL tunnel should not be mutually exclusive since a MySQL SSL connection can be wrapped inside SSH tunnel.

### ISSUE THREAD

**Issue by Kartikwy** [webyog/sqlyog-community#2096]
With the emerging cloud services, the use of SSL connection through an SSH tunnel is required in many cases. The user in the ticket No. 145969 wants that SQLyog should support the SSL encryption through an SSH tunnel.

**Comment by exussum12** [comment]
Until this is an official feature, You can use a local port forward though putty and connect to that port though sqlyog which would support this
