### ISSUE TITLE
UTF8 character encoding problem

### ISSUE THREAD

**Issue by piotrku** [webyog/sqlyog-community#2098]
there's a problem with character encoding (field values, field comments in table structure)
I've check the correct data encoding - DB and table fields are UTF8, all data is correctly displayed when using PHPmyAdmin or on Wordpress site but in the SQLyog I see incorrect characters like: "Nag��wek"

tested on version 12.13,
newest version 12.19 crashes when trying to display table settings (structure)

**Comment by peterwy** [comment]
You are probably affected by this
http://faq.webyog.com/content/34/152/en/my-special-characters-display-as-_noisy_-latin-characters-in-sqlyog.html

It is not an issue with SQLyog. 

Besides this issuetracker is notthe right place for such discusson. Please use our Forums or send a mail to support@webyog.com.

Closing this invalid report.

**Comment by peterwy** [comment]
BtW: it also may be becaue the fonts you use don't have full unicode support.

But please use the other contact options. This is not a place for discussion
