### ISSUE TITLE
12.1.9 unstable when browsing table data

### ISSUE THREAD

**Issue by brucekirkpatrick** [webyog/sqlyog-community#2100]
Has anyone reported easily reproducible hang/crash when trying to browser table data in sqlyog community 12.1.9 (32-bit)?   In addition to crashing, it is incredibly slow when it works, regardless of whether the server is remote or not.   I have to force close the program in windows to be able to use it again.

Downgrading to 12.1.8 completely fixes the problem.

**Comment by LFCaine** [comment]
Yes, same here.  Tried both 64 bit and 32 bit.  It was completely broken to the point of hanging constantly.  I couldn't even use the scrollbars without it hanging.  12.1.8 works perfectly.

**Comment by Kartikwy** [comment]
We have had similar issues reported by other users. Thanks for reporting it. We have identified the issue and it is fixed in the next release which can be expected in another 6 hrs. Thanks for your patience in advance. You can write to support@webyog.com for any other queries you have.

Thanks

**Comment by Kartikwy** [comment]
This issue is fixed in our latest release..Please refer to our blog here..>> 
(​http://blog.webyog.com/2016/02/12/sqlyog-mysql-gui-12-2-0-released/)
​
