### ISSUE TITLE
The letter in SQLyog browser looks vaguely.

### ISSUE THREAD

**Issue by SangYoop** [webyog/sqlyog-community#2102]
I changed my laptop and installed sqlyog in my computer.

When I open the yog, I found that letters in yog looks vaguely like a below photo. 

![default](https://cloud.githubusercontent.com/assets/16567945/13118188/6464127c-d5e6-11e5-97b5-6ed0fd6d167f.png)

What is the problem? Other program is fine like Rstudio and eclipse.

**Comment by peterwy** [comment]
Please contact us at support@webyog.com or use our Forums.  An issue tracker is not a proper place for support.

We need information like:
* Your SQLyog version? There was an important change in this regard in version 12.05.  Refer http://blog.webyog.com/2015/01/28/sqlyog-mysql-gui-12-05-released/ "Changed the rendering mechanism used on high-resolution..."
* Your Windows version (10, right?)
* monitor resolution?
* scaling setting for the monitor

Refer this Micrsosoft document on how various WIndowsversions handle high resolution monitors: 
https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx


But please reply to the questions in a mail to support@webyog.com (or use our Forums) and not here.
