### ISSUE TITLE
Copy database should auto detect if there exists a table with the same name in the target as the source.

### ISSUE THREAD

**Issue by Kartikwy** [webyog/sqlyog-community#2104]
In copy database when a table is selected for copying, SQLyog should automatically place the name of the table in the option selected if the name is same in source and the target.
Please refer HS ticket #164764

**Comment by sibwy** [comment]
This option to auto detect the database if there exists a database with the same name in the target as the source is added in SQLyog 12.3.0 release. The release notes can be referred from the blog >> https://blog.webyog.com/introducing-gui-transaction-support-in-sqlyog-12-3-0/
