### ISSUE TITLE
Larger click area to drag the window separator 

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2105]
Couple of users have asked for a larger click area around the separator between the Query window and Result window to drag and resize the window. 

The user request in the forums >> http://forums.webyog.com/index.php?showtopic=9347 and http://forums.webyog.com/index.php?showtopic=9339

This also applies to the separator between Object browser and Query window.

**Comment by mclaborn** [comment]
Yes please!

**Comment by JoeC57** [comment]
This would be nice

**Comment by sibwy** [comment]
We have added this feature in the latest release SQLyog 12.2.3. The width of the dividers between the “Query Editor" tab and “Result" tab of the SQLyog main window has been increased for better operability of resizing. The width of the dividers between the "Object browser" and "Query editor" tabs have also been increased.

The release notes can be referred here >> http://blog.webyog.com/2016/05/26/sqlyog-mysql-gui-12-2-3-released/
