### ISSUE TITLE
Set to null disabled

### ISSUE THREAD

**Issue by conyg** [webyog/sqlyog-community#2108]
There are fields that can be set to null even if column is set as "Not Null". One example is timestamp column with CURRENT_TIMESTAMP as DEFAULT. When this column is set to NULL MySQL will replace it with current timestamp value (so remains not null).

Please re-enable "Set To NULL" on "Table Data" right-click context menu.
![snap 2016-05-19 at 13 49 57](https://cloud.githubusercontent.com/assets/3230679/15409243/cc74e344-1dc8-11e6-9b9e-583bad4249c0.png)

**Comment by sibwy** [comment]
This issue has been fixed in SQLyog 12.2.5 release. The release notes can be referred from the blog >> http://blog.webyog.com/sqlyog-mysql-gui-12-2-5-released/
