### ISSUE TITLE
Adding Filter for drop-down list in User Manager

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2109]
An user has asked for an option to filter the users in the drop-down list in the ‘User Manager’, as the same way we filter the tables, databases and connections.

The user request can be found here >> http://forums.webyog.com/index.php?showtopic=9364

**Comment by sibwy** [comment]
We have added this feature in the latest release SQLyog 12.2.3. When some characters are typed for user in User Manager first match with same starting characters will be selected.

The release notes can be referred here >> http://blog.webyog.com/2016/05/26/sqlyog-mysql-gui-12-2-3-released/

**Comment by larsen0815** [comment]
Thanks, but this still needs some improvement:
- It is not possible to filter for a string in the middle of a username
- All the other users are still shown

As I stated in the forum, it would be best to have this filter work the same way as the filter for table names does.

**Comment by sibwy** [comment]
We have marked this request as open and we will look into this.

**Comment by larsen0815** [comment]
Thx!

**Comment by sibwy** [comment]
This feature has been added in SQLyog 12.2.5 release. The release notes can be referred from the blog >> http://blog.webyog.com/sqlyog-mysql-gui-12-2-5-released/

**Comment by larsen0815** [comment]
Great improvement, thx!
