### ISSUE TITLE
Line numbers incorrectly displayed in query window

### ISSUE THREAD

**Issue by tntc4** [webyog/sqlyog-community#2115]
I have one option checked "Restor session on startup".
when I previously have Query tab opened and populated with some text and lines in this query is more than 10 after close and reopen SQLyog these line numbers is not showed correctly.
after click inside this query and when query window has focused then line numbers showed correctly.
see screenshots:
1.after start and before focused
![screenshot_1](https://cloud.githubusercontent.com/assets/3246834/17050342/07a47a7e-4ffb-11e6-9764-8dab80e4a2bc.png)
2. after starts and focused
![screenshot_2](https://cloud.githubusercontent.com/assets/3246834/17050359/189c9bcc-4ffb-11e6-8dbb-8dcf968564d8.png)

**Comment by sibwy** [comment]
This issue has been fixed in SQLyog 12.2.5 release. The release notes can be referred from the blog >> http://blog.webyog.com/sqlyog-mysql-gui-12-2-5-released/
