### ISSUE TITLE
Incorrect tab selected after closing another tab

### ISSUE THREAD

**Issue by b4tch** [webyog/sqlyog-community#2116]
If you have 3 (or more) connection tabs open, follow these steps:

1 - Select tab 2
2 - Close tab 1 (without selecting it)
3 - Tab 3 should now be visually highlighted, but the connection actually remains on tab 2

**Comment by peterwy** [comment]
Why do you expect the behaviour you describe here? Does our documentation state anything like that? 

Besides this issue-tracker is not a proper place for discussions. Use our forums or mail support (support@ewbyog.com) instead, please.

**Comment by sibwy** [comment]
We did check this and found the issue (something similar as you reported). Here the test-case to reproduce,

Consider 3 open connection tabs

1) Select/Open tab2  
2) Close tab1 without clicking/selecting it
3) Contents of tab2 is displayed , but tab3 gets highlighted

Thank you for reporting. We will check this.

**Comment by b4tch** [comment]
Thanks for your (actually useful) reply @sibwy

**Comment by sibwy** [comment]
This issue has been fixed in SQLyog 12.2.5 release. The release notes can be referred from the blog >> http://blog.webyog.com/sqlyog-mysql-gui-12-2-5-released/
