### ISSUE TITLE
MySQL error while inserting a string containing MySQL functions as text

### ISSUE THREAD

**Issue by jntx** [webyog/sqlyog-community#2121]
SQLYog version: 12.3.0
MySQL version: 5.7.14

On the inline editor, "Table Data" tab, I get a MySQL error when inserting a text that is valid MySQL code on a varchar/longtext column.
How to reproduce:
- let's create a table with varchar and/or longtext field:
CREATE TABLE texttest (
  id int(11) NOT NULL AUTO_INCREMENT,
  mytext varchar(200),
  mylongtext longtext,
  PRIMARY KEY (`id`)
);
- select the table texttest in the table tree on the left and go to the "Table Data" tab;
- enter the cursor in the mytext field and write the string "YEAR(mydate)" (without double-quotes);
- move down to the next row and a MySQL error appear showing the statement it tryed to run... something like the following: insert into `mydb`.`texttest` (`mytext`) values (YEAR(mydate))

The same behaviour happens for the longtext field.

This behaviour happens only when the string starts with a know MySQL function. If you add a character (even a space character) before the string (example " YEAR(mydate)") the problem disappears and the string is correctly escaped and stored in the DB.

**Comment by peterwy** [comment]
This is per design.

Please refer this FAQ:
http://faq.webyog.com/content/8/116/en/can-i-use-functions-with-sqlyog-data-and-result-panes.html


For further discussion please use our support email suppert@webyog.com

**Comment by jntx** [comment]
Found the setting in the preferences. Sorry for this false positive.
Thanks.
