### ISSUE TITLE
An option to open a connection as READ ONLY for a privileged user inside SQLyog

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2122]
By using this option, the user can use one credential and create different connections where in one connection, the user can execute all the queries and in the other, allowing the user to execute only the queries starting with : SHOW and SELECT

**Comment by mclaborn** [comment]
Great idea!

**Comment by exussum12** [comment]
Agreed useful feature :+1:

**Comment by exussum12** [comment]
This can now be closed ?

**Comment by sibwy** [comment]
This feature has been implemented in SQLyog 12.4.0 release. The release notes can be referred from the blog >> https://blog.webyog.com/adding-option-read-connections-sqlyog-mysql-gui-12-4/
