### ISSUE TITLE
Error while updating joined table (wine)

### ISSUE THREAD

**Issue by Infidel75** [webyog/sqlyog-community#2125]
I run this trivial query:

`select R.ID, UV.ID, UV.VALUE from `VEP_COMMON`.`REGISTER` as R 
left join `VEP_COMMON`.`FW_USER_VALUES` as UV on R.USER_ID=PID and UV.`KEY`='PROFILE_RIGHTS'
where R.`RKEY` = 'cr/list/menubuttons/toolsapp'; ` 

Result is as expected: grid with some rows in it.

Then I'd like to make some changes on joined table, so i switch dropdown menu from Read only to desired table to edit, exactly, in this case, "`VEP_COMMON`.`FW_USER_VALUES`"

Then I enter a cell (using F2), change value. Stil working as expected. 

But now, if I move to another row expecting saving changes, one of three possibilities occurs:
1. (most often) SQLyog freezes and I can only kill its process. Or
2. Mysql error dialog window is shown up with these texts:
`Executed SQL statement`
`update `VEP_COMMON`.`FW_USER_VALUES` set `VALUE` = 'TOOLS,' where `ID` = '1109'`
`Error  1064`
`Error message`
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE FIELD='VALUE' AND (Extra LIKE '%VIRTUAL%' OR Extra LIKE '%STORED%' OR Extr' at line 1`. Or
3. `SQLyog crashes` dialog window. (I am not sure with this text because it's hard to simulate).

So far it looks working (it saves values without problems) when using button "Save changes", but it's not too much comfortable.

--------------
OS: Linux mint 17.3
SQLyog Community v.12.3.2 (64 bit)
Wine 1.6.2

**Comment by peterwy** [comment]
We will check this. Expect an update next week.

**Comment by sibwy** [comment]
We are not able to reproduce this issue and works as expected for us. 

Can you please send us the table dumps with sample data to support@webyog.com so that we could try reproducing the issue?

**Comment by Infidel75** [comment]
Well, it seems there is one important thing: this issue occurs (only?) on Mysql version 4.1.15

> Variable_name;Value
protocol_version;10
version;4.1.15-Debian_1ubuntu5-log
version_comment;Source distribution
version_compile_machine;i486
version_compile_os;pc-linux-gnu

You may use this sql code for creating tables and running query:
[sql_code.txt](https://github.com/webyog/sqlyog-community/files/634301/sql_code.txt)
(Please note the table engine "MyISAM", is it relevant?)

Then try to edit "SOMETHING" field using F2 and save it by the down arrow key.

**Comment by peterwy** [comment]
http://faq.webyog.com/content/1/178/en/sqlyog-is-a-client-for-the-mysql-server-_-but-what-server-versions-are-supported.html

"If you for some reason need to stay with 4.1, we recommend 4.1.20 or higher."

I don't think we will be able to get 4.1.15 from anywhere today.  It is around 15 years old. But we have 4.1.21  or 4.1.22 somewhere I think.

**Comment by Infidel75** [comment]
Oh! I did not realize this possibility :-(
Your are right, I use SQLyog many years (but this issue started its occurence relatively recently). OK, I plan upgrading the mysql server (not so easy) so this problem will be solved soon.
I apologize myself for disturbing you. Please mark this issue as closed.
