### ISSUE TITLE
Highlighting the margin in the SQL query editor (SQL window)

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2126]
In the Query editor, there is no clear indication of where 1st position is as there is quite a few whitespace before the 1st position and due to this it looks like the cursor is indented already and not at 1st position.

The user request can be found in HS >> 232412

**Comment by wyaadarsh** [comment]
The customization is available in Preferences.

Goto Tools-> Preferences -> Font & Editor Settings -> Editor -> Line Number Margin -> Background Color.
