### ISSUE TITLE
Support for CHECK constraints

### ISSUE THREAD

**Issue by peterwy** [webyog/sqlyog-community#2146]
CHECK constrraints are supported in MariaDB 10.2+.  We should add support in CREATE/ALTER TABLE.

See discussion in ticket 295724/.  Note that the constraint is 'table-level'; not 'column-level - ie. the expression defining the constraint may reference more than one column.

Suggestion: In "CREATE/ALTER TABLE" GUI the "Foreing Keys" tab could be renamed to "Constraints" and the content of the tab altered to handle both types of constraints.

**Comment by sibwy** [comment]
Added CHECK constraint support with CREATE/ALTER TABLE GUI in v13.1.2
