### ISSUE TITLE
 SJA 12.5.0 (linux/64): Reports incorrect version 12.4.3

### ISSUE THREAD

**Issue by vstokesjr** [webyog/sqlyog-community#2153]
I just downloaded SJA for Linux x64 12.5.0 and when I do a "sja --version" it is reporting 12.4.3

**Comment by sibwy** [comment]
The version was missed out by an oversight. We will bring things in order with next release.

**Comment by sibwy** [comment]
This is rectified in SQLyog 12.5.1
