### ISSUE TITLE
Unable to connect to MySQL 8.0.4

### ISSUE THREAD

**Issue by YandyZaldivar** [webyog/sqlyog-community#2164]
This is due to the new default authentication plugin `caching_sha2_password`

**Comment by peterwy** [comment]
We know this.  We hope to provide support for this plugin soon.  But it may take some months.  Basically it is not an issue with SQLyog us such, but with the MariaDB Connector/C that we use in SQLyog. As soon as Connector/C supports the plugin we also will shortly after. 

The user that SQLyog connects with will need to be created with the old 'native password' - like
"CREATE USER username@hostname IDENTIFIED WITH 'mysql_native_password';"
.. and next you "SET PASSWORD .." and "GRANT .."

You will need to execute CREATE USER and GRANT from commandline (and as root@localhost). For instance if you from commandline do this:
CREATE USER yoguser@hostname IDENTIFIED WITH 'mysql_native_password';
GRANT ALL PRIVILEGES ON *.* TO yoguser@hostname WITH GRANT OPTION;
.. you can next connect with SQLyog as "yoguser".  And the GRANTs for this user is identical to 'root' @'localhost'. So from here you can do anything as 'yoguser' exactly as what you can as 'root'.

**Comment by peterwy** [comment]
Please correct typo.

GRANT ALL PRIVILEGES ON . TO yoguser@hostname WITH GRANT OPTION;

should be 

GRANT ALL PRIVILEGES ON *.* TO yoguser@hostname WITH GRANT OPTION;

**Comment by peterwy** [comment]
We bumped into a github issue.  It will not accept asterisk. I hope it is clear below:

GRANT ALL PRIVILEGES ON <asterisk>.<asterisk> TO yoguser@hostname WITH GRANT OPTION;

**Comment by peterwy** [comment]
GRANT ALL PRIVILEGES ON asterisk.asterisk TO yoguser@hostname WITH GRANT OPTION;

**Comment by peterwy** [comment]
Finally!

**Comment by netcse** [comment]
**Same Problem With SQLyog**

`Server version: 8.0.11 MySQL Community Server - GPL`

![mysql-conn-error](https://user-images.githubusercontent.com/2453604/39636851-382ec55c-4fe3-11e8-9b58-3b31bfb0490f.png)

**Comment by peterwy** [comment]
SQLyog needs to connect with the 'mysql_native_password' authentication method. Oracle introduced "caching_sha2_password" and made it default in MySQL 8.0.4 or 8.0.11. But this new authentication methoid does not yet have plugin support in the client code, we use in SQLyog (MariaDB's "Connector/C"). ACtually only clients and connector from Oracle can use the new authetication plugin. 

Before upgrading to MySQL version 8 you should understand this: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html


To create a user that SQLyog may connect specify the authentication method in a WITH-clause - like

CREATE USER 'sqlyoguser'@'%' IDENTIFIED WITH mysql_native_password BY 'mypass';

.. next GRANT what you want to grant. If 'sqlyoguser' should be as powerfull as root then it is:
GRANT ALL PRIVILEGES ON *.* TO 'sqlyoguser'@'%' WITH GRANT OPTION;

.. and now coonnect with SQLyog as 'sqlyoguser'.

**Comment by peterwy** [comment]
hmm .. some formatting happens here removing the <asterisk> character. The GRANT statement should be 

GRANT ALL PRIVILEGES ON <asterisk>.<asterisk>TO 'sqlyoguser'@'%' WITH GRANT OPTION;

**Comment by zabullet** [comment]
This appears to still be an issue. Have the drivers still not been updated 10 months later?

**Comment by illfated** [comment]
@peterwy : I think your statements will behave nicer if you use GitHub Flavored Markdown, surrounding the code with back ticks like **```** to start & end a code block:
```sql
GRANT ALL PRIVILEGES ON *.* TO yoguser@hostname WITH GRANT OPTION;
```
To highlight SQL syntax, you can preface your code block with **```sql** to do so.
- https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
- https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by smamran** [comment]
Create a user from `root` account, grant privileges and flush privileges
```
CREATE USER 'admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'nopass';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';
FLUSH PRIVILEGES;
```

**Comment by jaddie** [comment]
This still isn't implemented over a year later? Surely there is something that can be done to make sqlyog support this without having to do some crappy workaround, I guess I'll switch to navicat or mysql workbench then :(

**Comment by peterwy** [comment]
We will upgrade the connector to a new one that supports this authentication method in next release planned for the next 3-4 weeks.

**Comment by sdcg1994** [comment]
Is there any new ?

**Comment by peterwy** [comment]
If the very final tests go well, we will release v. 13.1.3 tommorrow with support for this authentication plugin.

**Comment by sibwy** [comment]
Support for "caching_sha2_password" authentication plugin is added in SQLyog v13.1.3
