### ISSUE TITLE
Option to include/exclude 'ROW_FORMAT' parameter in Schema sync

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2170]
ROW_FORMAT is not important for many users, it could be considered optional.  In particular, when comparing MySQL 5.6,5.5/MariaDB 10.2.1 (with 'COMPACT' as the default value) with MySQL 5.7+/MariaDB 10.2.2 (with 'DYNAMIC' as the default value), a lot of ALTER TABLEs are generated that user may want to discard. 

The user request can be found in HS >> #92487

**Comment by mclaborn** [comment]
Yes please. This came about when SQLyog 13 started taking ROW_FORMAT into account.

**Comment by peterwy** [comment]
One more ticket 540193658/61717

**Comment by sibwy** [comment]
We have released v13.0.1, where it is optional to include InnoDB Row Format in ALTER TABLE statements. Please refer to the release notes, [here](http://blog.sqlyog.com/sqlyog-mysql-gui-13-0-1-released/)
