### ISSUE TITLE
crash on select query with large number of columns

### ISSUE THREAD

**Issue by rbro** [webyog/sqlyog-community#2181]
I am running SQLyog Community 13.0.0 to run queries with a large number of columns.  I have noticed that if I have a query with >= 3,401 columns, SQLyog crashes the below info.  I posted an example query at https://pastebin.com/DPqgiyR3.  The query crashes for me, but if I remove the last column, then it runs successfully.  I am connecting to a MySQL server running 5.7, but seeing the same behavior against MySQL 5.6 too.  Can you please check into it?  Please let me know if I can supply any more information to reproduce it.

Problem signature:
  Problem Event Name:    BEX64
  Application Name:    SQLyogCommunity.exe
  Application Version:    13.0.0.0
  Application Timestamp:    5ac63c85
  Fault Module Name:    SQLyogCommunity.exe
  Fault Module Version:    13.0.0.0
  Fault Module Timestamp:    5ac63c85
  Exception Offset:    000000000001e969
  Exception Code:    c0000409
  Exception Data:    0000000000000000
  OS Version:    6.1.7601.2.1.0.256.48
  Locale ID:    1033

**Comment by sibwy** [comment]
This is because we have hardcoded the column limit to 3400 in our code. We will be fixing this in the next release.

**Comment by sibwy** [comment]
This is fixed in SQLyog v13.1.0

**Comment by rbro** [comment]
Could this issue please be reopened?  I'm now seeing this issue if the query has > 4096 columns.

**Comment by sibwy** [comment]
Please contact us on email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) so that we can get more details. The way we use GitHub is strictly as an issue-tracker and not for support or discussions. This is necessary in order to keep the system manageable.
