### ISSUE TITLE
MySQL 8.0 Not Supported

### ISSUE THREAD

**Issue by magz123** [webyog/sqlyog-community#2184]
This version of sqlyog does not support the new MySQL 8 connection

**Comment by peterwy** [comment]
It does support MySQL 8.0, but the user that SQLyog connects with will need to be created with the old 'native password' - like
"CREATE USER username@hostname IDENTIFIED WITH 'mysql_native_password';"
.. and next you "SET PASSWORD .." and "GRANT .."

You will need to execute CREATE USER and GRANT from commandline (and as root@localhost). For instance if you from commandline do this:
CREATE USER yoguser@hostname IDENTIFIED WITH 'mysql_native_password';
GRANT ALL PRIVILEGES ON <asterisk>.<asterisk> TO yoguser@hostname WITH GRANT OPTION;
.. you can next connect with SQLyog as "yoguser". And the GRANTs for this user is identical to 'root' @'localhost'. So from here you can do anything as 'yoguser' exactly as what you can as 'root'.

**Comment by peterwy** [comment]
Another reply

SQLyog needs to connect with the 'mysql_native_password' authentication method. Oracle introduced "caching_sha2_password" and made it default in MySQL 8.0.4 or 8.0.11. But this new authentication methoid does not yet have plugin support in the client code, we use in SQLyog (MariaDB's "Connector/C"). ACtually only clients and connector from Oracle can use the new authetication plugin.

Before upgrading to MySQL version 8 you should understand this: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html

To create a user that SQLyog may connect specify the authentication method in a WITH-clause - like

CREATE USER 'sqlyoguser'@'%' IDENTIFIED WITH mysql_native_password BY 'mypass';

.. next GRANT what you want to grant. If 'sqlyoguser' should be as powerfull as root then it is:
GRANT ALL PRIVILEGES ON . TO 'sqlyoguser'@'%' WITH GRANT OPTION;

.. and now coonnect with SQLyog as 'sqlyoguser'.

**Comment by peterwy** [comment]
BTW: All this has been reported before. Please search for identical issues before posting a report. The 2 replies above was pasted from previous replies. 

And please don't use the issue-tracker system to ask support.  Contact us at support@webyog.com instead.

**Comment by peterwy** [comment]
closing here!

**Comment by magz123** [comment]
>
> i’m sorry i thought it’s ok to post here since its the community version..
> however thanks for the info :) and about the connection problem i
> reinstalled mysql 8 then used the legacy support for old clients and it
> works..


CLOSED


-- 
via mobile
