### ISSUE TITLE
Sqlyog doesn't save the value in Mysql properly, I am wasting time with it, Please make it more stable.

### ISSUE THREAD

**Issue by anirugu** [webyog/sqlyog-community#2186]
I am copying the html into mysql column by open the table. AIK I can move my cursor to another row and it will save the changes, it's work but it's doesn't work all time.

 I have 4 column (without any primary key), I first put the value in last one, and 2nd last 3rd last and first.

sometime it doesn't store value for first and 2nd (start from 0). Someone look into this issue. I am using sqlyog from yesterday and this thing bugging me a lot.

can't reproduce, let me know I will come to your Bangalore office (yeah, I live in India) or able to send you screenshot.

**Comment by peterwy** [comment]
Please do not user our issue tracker system to ask support.

You should contact us at support@webyog.com instead or use our Forums. But I wonder if you have floating points data types in the table? If so, please read http://faq.webyog.com/content/29/162/en/tables-with-floating-point-datatypes-fail-to-update.html.

It is generally not wise not to have a Primary Key. And that is in particular true if the table has floating point data types.

**Comment by anirugu** [comment]
The first column is enum and other 3 is (2 is varchar, and last one is text).

it should tell it's failed just after I loose focus and it's failed. or somehow show it through UI, I seen this when I enter many records and see that some are null.

Ok, I will report to through mail. Thanks

**Comment by anirugu** [comment]
I send the mail to support guys and they are not available at the time I am free. they tell me they will monitor this thread for future.
so here is the problem,

1.  I have entering rows 27 one by one,
1.1 in one case overflow (sqlyog should tell me it's overflow) and it's not updating, NULL is set there where it's overflowing.

2. In the second case, I am not getting why it's failed but it doesn't take my entry this is a bug that I am talking about.

I update it as support guys reply me that they monitor it, no means to break the rules of this repos. 

Thanks

**Comment by peterwy** [comment]
Closing.  This is not an *issue*.  it is a *support* request.  problem seems to be related to (non-strict) SQL_mode used.

All has been communicated to user over mail.
