### ISSUE TITLE
Duplicate Current Row is always greyed out

### ISSUE THREAD

**Issue by adam-kelsey** [webyog/sqlyog-community#2187]
Is the duplicate current row ability a professional version only thing? I have the latest version of sqlyog and I am not in read only mode, but my duplicate current row is always greyed out. My co-worker has the exact same set up as me with the only difference being he uses the pro version.

Any thoughts?

**Comment by peterwy** [comment]
Please contact us on mail at support@webyog.com about this. The way we use github is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
