### ISSUE TITLE
Time to update PLINK

### ISSUE THREAD

**Issue by peterwy** [webyog/sqlyog-community#2188]
PuTTY introduced support for Ed25519 -keys in v. 0.68. We are currently (June 2018) on PLINK v. 0.67 that supports RSA keys only. So time to update PLINK as bundled with SQLyog.

We had a single user report in ticket 93271.

**Comment by sibwy** [comment]
The patched putty version in SQLyog is updated to v0.7 in SQLyog 13.1.0

**Comment by kshatri** [comment]
I am using the SQLyog 13.1.1-0 and still have issues connecting. I get Unable to start Plink 2: The system cannot find the file specified. How can i check If SQlyog is using the plink or not.
