### ISSUE TITLE
I need language pt-br

### ISSUE THREAD

**Issue by NuskyDEV** [webyog/sqlyog-community#2191]
You could make a version of the program with the portuguese language brazil.

**Comment by sibwy** [comment]
Please refer this blog >> [http://blog.sqlyog.com/how-to-localize-sqlyog/](http://blog.sqlyog.com/how-to-localize-sqlyog/
)
However the resources for localization is now on github at [https://github.com/webyog/sqlyog-community/tree/master/localization](https://github.com/webyog/sqlyog-community/tree/master/localization) (and not googlecode as was the case when the blog was written).

Translating SQLyog to a new language is a major undertaking (what you might realize already).

.. so there are 3 steps basically.

1. Create a new Spanish language file with translated strings (and remember to manage the Windows API markup system for keyboard shortcuts. For instance "save" is possibly not (probably not) "Alt+s" in Spanish)
2. Compile the new file into the l10n.db file using the "compile.bat" utility
3. Replace l10n.db on the system(s) where SQLyog is installed with the new file you just created.
