### ISSUE TITLE
[Bug?] The menu 

### ISSUE THREAD

**Issue by Tox86** [webyog/sqlyog-community#2192]
Hello, the menu does not show the complete sentence of the option.

Sorry my laptop is old (2013).
Windows 10 64 bits.
Screen: 1366x768.
![menu](https://user-images.githubusercontent.com/7013508/44558418-6a58e880-a71a-11e8-9df5-008575a8ba17.gif)

Cheers.

**Comment by sibwy** [comment]
We are aware of this issue, but we are unable to find a reproducible case. Are you able to reproduce this at will?
