### ISSUE TITLE
Unable to connect to Mariadb Using SQlyog 

### ISSUE THREAD

**Issue by kshatri** [webyog/sqlyog-community#2202]
Hi,

I have downloaded and installed SQLyog-13.1.1.-0.x64 and I an unable to ssh or establish mysql connection.

Error:
Unable to start Plink
2:The system cannot find the file specified.

When I click ok another error

SSH Error:FATAL ERROR: Network error:Connection timed out

SSH Port 22 and Mysql port 3306 are open from my VDI to the server. Tested with telnet and its working fine.

Please, suggest,

**Comment by davidjhall** [comment]
Hate to "me too" but also having this issue against mysql 5.6 on redhat.  Putty works fine and other programs that usually connect to mysql work fine too.

**Comment by sibwy** [comment]
Please contact us on email at [ideramysqlsupport@idera.com](mailto: ideramysqlsupport@idera.com) about this. The way we use github is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.

**Comment by rajesh17692pimcore** [comment]
@davidjhall  have you found any solution I am also facing the similar problem

SSH Error:FATAL ERROR: Network error:Connection timed out

**Comment by KoteKotlyarov** [comment]
@rajesh17692pimcore I have faced the same error message with 13.1.9.

SQLyog Ultimate v12.2.6 shows different error: `SSH Error: FATAL ERROR: Couldn't agree a key exchange algorithm` with a list of available ones.

From the other hand, Putty agent connects to the remote host normally. Remote host has access to the desired DB cluster. If Putty connects then probably app didn't support algorithm with which `ppk` key was generated from the `pem` file...
