### ISSUE TITLE
Alter table GUI issue - Unsigned checkbox checked for a column of 'enum' datatype

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2203]
Steps to reproduce:
1) Create the below table,

CREATE TABLE `dev_a4_pdns`.`test` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `unsigned` ENUM ('test', 'unsigned') NOT NULL,
  PRIMARY KEY (`id`)
);

2) Alter the table using the UI or "F6" keyboard shortcut. This will produce:

ALTER TABLE `dev_a4_pdns`.`test`
  CHANGE `unsigned` `unsigned` ENUM ('test', 'unsigned', 'test2')
CHARSET latin1 COLLATE latin1_swedish_ci **UNSIGNED** NOT NULL;

After editing, the alter statement reports the syntax error. This error is because the 'Unsigned' checkbox is checked for the column with 'enum' datatype.

Refer the image for reference.
![alter table ui issue](https://user-images.githubusercontent.com/15195164/48548571-5117a080-e8f3-11e8-997d-ed94b5128222.png)

The user report can be found in SF >> 00662864

**Comment by illfated** [comment]
I do not know if this is a rule or requirement, but it is usually recommended to avoid using internal SQL keywords as column names.
I would have tried to use a different name than `unsigned` as a column name.

**Comment by sibwy** [comment]
Fixed in v13.1.6
