### ISSUE TITLE
Implement "Ctrl+C" key event  to copy to clipboard <schema_name>.<table_name> on object browser

### ISSUE THREAD

**Issue by woogeee** [webyog/sqlyog-community#2213]
Sometimes, I need <schema_name>.<table_name> text when I write complex query.

I want to add the code what implement "Ctrl+C" key event  to copy to clipboard <schema_name>.<table_name> on object browser.

How do you think?

**Comment by illfated** [comment]
Currently, the way I would need to copy that combination to clipboard OS memory, I would place the cursor on a blank line, double-click the DB name, then add the period directly from the keyboard, then double-click the table name. Finally, I would select the full line and use Ctrl-C on that selection.

Still, I don't know the scenario where it is most needed or if many users would really need or depend on that feature to be a one-click or one key command.

**Comment by sibwy** [comment]
The reply from @illfated is the solution to the question here.

Another workaround is selecting the respective table in the 'Object Browser' and viewing its' data in the 'TableData' tab -> then go to the 'History' tab where you can copy the <schema_name>.<table_name> from the query used by SQLyog to populate the data in the 'TableData' tab.

FYI, you may clear the 'History' tab contents by right-clicking inside the tab and selecting the option 'Remove History' if the 'History' tab is cluttered by a lot of queries before performing the above workaround.
