### ISSUE TITLE
Close without error message

### ISSUE THREAD

**Issue by jejedu67** [webyog/sqlyog-community#2218]
Hi,

Each time I click on "alter table", SQLYog Community close without error message. But it happens only with tables on my first server. On the second server there is no problem if I want to alter table.

Version=1
EventType=BEX64
EventTime=131993921304579978
ReportType=2
Consent=1
UploadTime=131993921306575770
ReportStatus=268435456
ReportIdentifier=f16edc84-4175-433f-b7ca-990c0194616c
IntegratorReportIdentifier=bb788c0c-4af8-4bf3-a94f-e04fff03133b
Wow64Host=34404
NsAppName=SQLyogCommunity.exe
OriginalFilename=SQLyog.exe
AppSessionGuid=00002ca4-0004-000e-3c8d-12a3c5efd401
TargetAppId=W:0006163dc2ee8496dc28901a7260f6b3a18700000904!0000e9b56350676b4f887482f458b004026155582e08!SQLyogCommunity.exe
TargetAppVer=2018//12//28:10:44:57!0!SQLyogCommunity.exe
BootId=4294967295
TargetAsId=9042
UserImpactVector=808452912
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=3cbf3acfb4212d7095f7f9c59e697c6c
Response.BucketTable=5
Response.LegacyBucketId=1583008421205605484
Response.type=4
Sig[0].Name=Nom de l’application
Sig[0].Value=SQLyogCommunity.exe
Sig[1].Name=Version de l’application
Sig[1].Value=13.1.2.0
Sig[2].Name=Horodatage de l’application
Sig[2].Value=5c25fea9
Sig[3].Name=Nom du module par défaut
Sig[3].Value=dbgcore.DLL_unloaded
Sig[4].Name=Version du module par défaut
Sig[4].Value=10.0.17763.1
Sig[5].Name=Horodateur du module par défaut
Sig[5].Value=590c013e
Sig[6].Name=Décalage de l’exception
Sig[6].Value=0000000000006790
Sig[7].Name=Code de l’exception
Sig[7].Value=c0000005
Sig[8].Name=Données d’exception
Sig[8].Value=0000000000000008
DynamicSig[1].Name=Version du système
DynamicSig[1].Value=10.0.17763.2.0.0.768.101
DynamicSig[2].Name=Identificateur de paramètres régionaux
DynamicSig[2].Value=1036
DynamicSig[22].Name=Information supplémentaire n° 1
DynamicSig[22].Value=aa4c
DynamicSig[23].Name=Information supplémentaire n° 2
DynamicSig[23].Value=aa4c0824cd685891394893dd7e26734d
DynamicSig[24].Name=Information supplémentaire n° 3
DynamicSig[24].Value=bca7
DynamicSig[25].Name=Information supplémentaire n° 4
DynamicSig[25].Value=bca7ee06a168403c0fc4c29287929922
UI[2]=C:\Program Files\SQLyog Community\SQLyogCommunity.exe
LoadedModule[0]=C:\Program Files\SQLyog Community\SQLyogCommunity.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\WS2_32.dll
LoadedModule[5]=C:\Windows\System32\RPCRT4.dll
LoadedModule[6]=C:\Windows\SYSTEM32\SHFOLDER.dll
LoadedModule[7]=C:\Windows\System32\msvcrt.dll
LoadedModule[8]=C:\Windows\System32\SHELL32.dll
LoadedModule[9]=C:\Windows\System32\ole32.dll
LoadedModule[10]=C:\Windows\System32\combase.dll
LoadedModule[11]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[12]=C:\Windows\System32\ucrtbase.dll
LoadedModule[13]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17763.404_none_05b33d58072110de\COMCTL32.dll
LoadedModule[14]=C:\Windows\SYSTEM32\WININET.dll
LoadedModule[15]=C:\Windows\System32\shcore.dll
LoadedModule[16]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[17]=C:\Windows\System32\GDI32.dll
LoadedModule[18]=C:\Windows\System32\windows.storage.dll
LoadedModule[19]=C:\Windows\System32\gdi32full.dll
LoadedModule[20]=C:\Windows\System32\msvcp_win.dll
LoadedModule[21]=C:\Windows\System32\advapi32.dll
LoadedModule[22]=C:\Windows\System32\sechost.dll
LoadedModule[23]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.17763.404_none_369e303d61b38aac\gdiplus.dll
LoadedModule[24]=C:\Windows\System32\USER32.dll
LoadedModule[25]=C:\Windows\System32\profapi.dll
LoadedModule[26]=C:\Windows\System32\win32u.dll
LoadedModule[27]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[28]=C:\Windows\System32\powrprof.dll
LoadedModule[29]=C:\Windows\System32\COMDLG32.dll
LoadedModule[30]=C:\Windows\System32\kernel.appcore.dll
LoadedModule[31]=C:\Windows\System32\cryptsp.dll
LoadedModule[32]=C:\Program Files\SQLyog Community\SSLEAY32.dll
LoadedModule[33]=C:\Program Files\SQLyog Community\LIBEAY32.dll
LoadedModule[34]=C:\Windows\SYSTEM32\MSIMG32.dll
LoadedModule[35]=C:\Program Files\SQLyog Community\htmlayout.dll
LoadedModule[36]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[37]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[38]=C:\Program Files\SQLyog Community\MSVCR120.dll
LoadedModule[39]=C:\Windows\System32\IMM32.dll
LoadedModule[40]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[41]=C:\Windows\SYSTEM32\OLEACC.dll
LoadedModule[42]=C:\Windows\SYSTEM32\urlmon.dll
LoadedModule[43]=C:\Windows\SYSTEM32\iertutil.dll
LoadedModule[44]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[45]=C:\Windows\SYSTEM32\uxtheme.dll
LoadedModule[46]=C:\Windows\system32\napinsp.dll
LoadedModule[47]=C:\Windows\system32\pnrpnsp.dll
LoadedModule[48]=C:\Windows\System32\mswsock.dll
LoadedModule[49]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[50]=C:\Windows\System32\NSI.dll
LoadedModule[51]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[52]=C:\Windows\System32\winrnr.dll
LoadedModule[53]=C:\Windows\system32\NLAapi.dll
LoadedModule[54]=C:\Windows\system32\wshbth.dll
LoadedModule[55]=C:\Program Files\Bonjour\mdnsNSP.dll
LoadedModule[56]=C:\Windows\System32\rasadhlp.dll
LoadedModule[57]=C:\Program Files\SQLyog Community\SciLexer.dll
LoadedModule[58]=C:\Windows\SYSTEM32\Riched20.dll
LoadedModule[59]=C:\Windows\SYSTEM32\USP10.dll
LoadedModule[60]=C:\Windows\SYSTEM32\msls31.dll
LoadedModule[61]=C:\Windows\System32\MSCTF.dll
LoadedModule[62]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[63]=C:\Windows\System32\CRYPT32.dll
LoadedModule[64]=C:\Windows\System32\MSASN1.dll
LoadedModule[65]=C:\Windows\SYSTEM32\SspiCli.dll
LoadedModule[66]=C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[67]=C:\Windows\SYSTEM32\winhttp.dll
LoadedModule[68]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[69]=C:\Windows\SYSTEM32\TextInputFramework.dll
LoadedModule[70]=C:\Windows\SYSTEM32\CoreMessaging.dll
LoadedModule[71]=C:\Windows\SYSTEM32\CoreUIComponents.dll
LoadedModule[72]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[73]=C:\Windows\SYSTEM32\wintypes.dll
LoadedModule[74]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[75]=C:\Windows\System32\bcrypt.dll
LoadedModule[76]=C:\Windows\System32\clbcatq.dll
LoadedModule[77]=C:\Windows\system32\dataexchange.dll
LoadedModule[78]=C:\Windows\system32\d3d11.dll
LoadedModule[79]=C:\Windows\system32\dcomp.dll
LoadedModule[80]=C:\Windows\system32\dxgi.dll
LoadedModule[81]=C:\Windows\system32\twinapi.appcore.dll
LoadedModule[82]=C:\Windows\system32\RMCLIENT.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17763
OsInfo[3].Key=ubr
OsInfo[3].Value=404
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1036
OsInfo[7].Key=geoid
OsInfo[7].Value=84
OsInfo[8].Key=sku
OsInfo[8].Value=101
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=13181
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.379.17763.0-11.0.115
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16324
OsInfo[19].Key=svolsz
OsInfo[19].Value=237
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180914
OsInfo[22].Key=bldtm
OsInfo[22].Value=1434
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs5_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17763.404.amd64fre.rs5_release.180914-1434
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Core
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Fonctionnement arrêté
ConsentKey=BEX64
AppName=SQLyog - MySQL GUI - 64 bit
AppPath=C:\Program Files\SQLyog Community\SQLyogCommunity.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=3D7C0E759710372F27E568C073CA84EA
MetadataHash=-1063391008

![Screenshot_1](https://user-images.githubusercontent.com/25781475/55901814-6a82f700-5bca-11e9-9f79-db4d49c1dcd3.png)

**Comment by sibwy** [comment]
Please contact us at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com). An issue tracker is not a proper place for support. We add the issues/requests here in GitHub once we validate them.

We need information like:
1. Your SQLyog version?
2. The MySQL server version for which you are facing the problem
3. The MySQL server version for which **you are not facing the problem**

But please reply to the questions in a mail to [ideramysqlsupport@idera.com](ideramysqlsupport@idera.com) and not here.
