### ISSUE TITLE
Copy Database fails with the error "Unknown database 'mysql_native_password'"

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2232]
When there is a forced/unforced interruption of the internet connection where SQLyog is running, on performing a "Copy Database To Different Host/Database" it would fail with the error `Error No. 1049  Unknown database 'mysql_native_password'`

The user reports can be found in SF >> 00766114, 00767771, 00790656, 00805152, 00808865, 00814786

**Comment by blimvere** [comment]
This appears to have been introduced in 12.6. I downgraded to 12.5 and the error does not occur.

**Comment by sibwy** [comment]
Fixed in [v13.1.8](https://blog.sqlyog.com/sqlyog-mysql-gui-13-1-8-release/).
