### ISSUE TITLE
LOAD DATA LOCAL INFILE query fails when executed manually

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2240]
The query generated by '**Import CSV Data Using LOAD LOCAL...**' and '**Import XML Data Using LOAD LOCAL...**' table import options when executed manually fails with the below error, though the SQLyog's import using LOAD LOCAL option works fine. 

    "Error Code: 2000  Load data local infile forbidden".     

But when the LOAD LOCAL query is executed in a new connection to the same server in SQLyog, then it works as expected.

On removing the 'LOCAL' modifier, the query is executed successfully, but the prerequisite is that the data file needs to be on the server host.

The 'local_infile' variable always enabled for all the above cases.

The user report can be found in SF >> 00780618

**Comment by sibwy** [comment]
Another user report, [here](https://github.com/webyog/sqlyog-community/issues/2265).

**Comment by wl-sqlyog** [comment]
Is there any update/solution on this issue ? I have checked that this problem cames up with SQLYog 13.1.3 and still in 13.1.7. Release 13.1.2 was the last version where LOAD DATA LOCAL INFILE succeeded.
Mentioned bypass/workaround with opening new connection does not help. Doing load via GUI is no valid solution because we have a lot of scripts to do work.

**Comment by illfated** [comment]
@wl-sqlyog : The issue is most likely not resolved, otherwise this ticket would have been closed with a closing comment about the solution.

**Comment by sibwy** [comment]
Fixed in [v13.1.8](https://blog.sqlyog.com/sqlyog-mysql-gui-13-1-8-release/).

**Comment by richie-chauhan** [comment]
Not entirely sure...but it seems that there are restrictions on some folders. Haven't found anything else. Would be great if someone confirms this behaviour on the thread. 

The same file worked when uploaded from my desktop. 

Did not work from 
* /tmp/
* /home/me/Downloads/

Worked from 
* /home/me/Desktop

**Comment by werner02815** [comment]
only working with Windows. In Windows i do not see any restriction on folders (successfully used your mentioned ones). I am using V13.1.9 (64Bit)
