### ISSUE TITLE
'Copy Tables to different host' returns an error

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2244]
If SQLyog has been running during the night and on right-clicking on a table and selecting "Copy Table(s) To Different Host/Database..." option and then selecting another connection to copy the table to the next morning will return the error "**Error No. 1043 Bad Handshake**". 

The error occurs even for the connection where 'Session Idle Timeout' and 'Keep-Alive Interval' is set.

The user report can be found in SF >> 00785262, 00819184

When this error pops-up with the 'Copy Tables ...' option, selecting the menu "File -> New Connection Using Current Settings" also results in the same error.

**Comment by illfated** [comment]
If it had not been for the stressful times we are in, it could have been fun to make a social distancing joke about that error message.

**Comment by sibwy** [comment]
Another user report for the same issue in SF >> 00803168

**Comment by SendiMyrkr** [comment]
Guys do something with that, it's so frustrating.

**Comment by illfated** [comment]
@SendiMyrkr : I am certain it is being worked on. I presume you will need to follow the issue in the correct forum pages to get any updates about the issue status.

**Comment by sibwy** [comment]
In the interim please find the different workarounds for this problem and you could consider the one that you find the best,

1) Create a database with the name "mysql_native_password" and give the respective MySQL user the access to read
or,

2) Close the respective connection tab and reconnect
or,

3) Close and re-open SQLyog. Ensure you have the 'Restore session on startup' feature enabled and also save the current session manually (from the 'File' menu) as well for a safer side.

**Comment by sibwy** [comment]
Fixed in [v13.1.8](https://blog.sqlyog.com/sqlyog-mysql-gui-13-1-8-release/).

**Comment by phirilesly** [comment]
disconnect all and start again to connect
