### ISSUE TITLE
Schema sync reports differences though there are no differences in schema

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2247]
Though the structure of the table is the same in both source and target servers (versions mentioned below), the schema sync still reports the difference and on syncing the difference, the same difference is reported again.

Source server: MariaDB 10.1.21
Target server: MySQL 8.0.19

The user report can be found in SF >> 00795146

**Comment by kanchisaxena** [comment]
Automation Details:
We have automated the test cases for this ticket and execution is completed. Please find the attached Ranorex log report.
Build: SQLyog-13.1.8-6
[Issue_2274_log.zip](https://github.com/webyog/sqlyog-community/files/6264008/Issue_2274_log.zip)

**Comment by sibwy** [comment]
Fixed in [v13.1.8](https://blog.sqlyog.com/sqlyog-mysql-gui-13-1-8-release/).
