### ISSUE TITLE
Silly design with multiple tags!

### ISSUE THREAD

**Issue by wow93930** [webyog/sqlyog-community#2253]
Multiple query, click on a new table, the other query TAB results are also updated to this table..I've looked all over the Settings. I can't find any key close the stupid function  . This design is stupid..If I just look at one table... and you need more query tags?

**Comment by sibwy** [comment]
Please contact us on email at ideramysqlsupport@idera.com so we could get more details on it. Once we verify if there is an issue, we will then add it to GitHub and it is necessary in order to keep the reports manageable.
