### ISSUE TITLE
Sqlyog API or command line

### ISSUE THREAD

**Issue by waltergrimmvie** [webyog/sqlyog-community#2254]
HI, i cant find anythign on this, and cannot login to community with my username and password.

MY questions please. Is there any way to use the DB compare functions from SQL using a command line or API please

WHY: i have more than 1 server, and would like to make a dump of DB on servers, run an automatic install of the dump on my dev server where mysql log and main DB is sinstalled, and run a compare

thanxs

Walter

**Comment by sibwy** [comment]
Please contact us on email at ideramysqlsupport@idera.com. The way we use GitHub is strictly as an issue-tracker for known issues and not for support/discussions. This is necessary in order to keep the system manageable.
