### ISSUE TITLE
Bad handshake with mariadb MariaDB 10.3.23

### ISSUE THREAD

**Issue by woots29** [webyog/sqlyog-community#2256]
We recently upgraded our mariadb but when we used this to copy db to db, there's an error indicated
 `Error no.1043
 Bad handshake`
We can't find workarounds online.

**Comment by sibwy** [comment]
We are already aware of this issue and is recorded [here](https://github.com/webyog/sqlyog-community/issues/2244).

Currently, we do not have a resolution. But we assume this could be an issue with the MariaDB connector which we use in SQLyog to make connections to the server and hope this gets resolved on upgrading the connector which is scheduled for the coming release.
