### ISSUE TITLE
SQLyog doesn't set passwords for existing users

### ISSUE THREAD

**Issue by larsen0815** [webyog/sqlyog-community#2257]
I have tested this with SQLyog 13.1.6 on servers running Debian Stretch (MariaDB 10.1) and Debian Buster (MariaDB 10.3).

Creating a user works fine, but when I change the password afterwards via User Manager, nothing happens. The password is not changed as I can see from the table mysql.user and SQLyog's history doesn't show any action.

Win 10, 1909

**Comment by sibwy** [comment]
We are aware of this issue. This is a regression bug introduced by fixing the issue mentioned, [here](ttps://github.com/webyog/sqlyog-community/issues/2221)

This issue will be fixed in the coming release.

**Comment by sibwy** [comment]
Fixed in [v13.1.7](https://blog.sqlyog.com/sqlyog-mysql-gui-13-1-7-released/)
