### ISSUE TITLE
SQLyog crashes with HTTP tunnel

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2267]
On executing a "SELECT ..." statement with large no. of rows (like 10,000 rows) and then selecting the "Copy All Rows To Clipboard" option in the 'Result' tab in a connection via HTTP tunnel, SQLyog closes abruptly and no crash dump is created.

This issue is not reproducible on viewing the data in the 'Table Data' tab as well as while limiting the rows to 1000 in the "SELECT ..." statement.

Reproducible using the SQL script attached here >> [HTTP_issue.zip](https://github.com/webyog/sqlyog-community/files/5463262/HTTP_issue.zip)

The user report can be found in SF >> 00818807

**Comment by IGedeon** [comment]
One year later... even with premium support the issue is abandoned. I can not see any value from the paid support I guess the best choice is not to renew

**Comment by sibwy** [comment]
Fixed in SQLyog [v13.2.0](https://webyog.com/blog/sqlyog/new-release-sqlyog-13-2-0/)
