### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by lucalas** [webyog/sqlyog-community#2269]
Hi, is possible to make a portable edition og sqlyog community?

**Comment by illfated** [comment]
At first, I thought I would have a clear answer to this, but while browsing the code it seems you would need to get an answer from the webyog developer team.

BTW, wouldn't this question fit better in the forum pages?

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
