### ISSUE TITLE
Indexes not displayed with MariaDB System-Versioned tables

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2270]
Reproducible with the below table,
    
    CREATE TABLE `t1` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `info` TEXT NOT NULL,
    `sub_id` INT(11) NOT NULL,
    `user` INT(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `sub_id` (`sub_id`),
    KEY `user` (`user`)
    ) ENGINE=INNODB DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

The user report can be found in SF >> 00862855

**Comment by kanchisaxena** [comment]
Automation Details:
We have automated the test cases for this ticket and execution is completed. Please find the attached Ranorex log report.
Build: SQLyog-13.1.8-6
[Issue_2270_log.zip](https://github.com/webyog/sqlyog-community/files/6263985/Issue_2270_log.zip)

**Comment by sibwy** [comment]
Fixed in [v13.1.8](https://blog.sqlyog.com/sqlyog-mysql-gui-13-1-8-release/).
