### ISSUE TITLE
Schema sync fails to sync the mismatch

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2272]
The Schema sync tool detects the schema mismatch, but after executing the query generated by the tool, the tool fails to sync the difference and still displays the schema mismatch.

The source and target server version is MySQL v8.0.15

The user report (and the reproducible data shared by the user) can be found in SF >> 00866912

**Comment by kanchisaxena** [comment]
Automation Details:
We have automated the test cases for this ticket and execution is completed. Please find the attached Ranorex log report.
Build: SQLyog-13.1.8-6
[Issue_2272_log.zip](https://github.com/webyog/sqlyog-community/files/6264023/Issue_2272_log.zip)
