### ISSUE TITLE
MySQL 8.0 databases cannot have max_queries_per_hour updated via User Manager interface

### ISSUE THREAD

**Issue by brymck1** [webyog/sqlyog-community#2278]
Connect to a MySQL 8.0 database
Open User Manager by clicking on button of person
Create a new user and specify non-zero values for Maximum number of queries per hour, Maximum number of updates per hour, Maximum number of connections per hour, or Maximum number of user connections

MySQL error pops up, attempting to run "GRANT USAGE ON *.* to 'username'@'%' WITH MAX_USER_CONNECTIONS 100"

MySQL 8.0 doesn't use GRANT USAGE to alter these parameters any longer, it uses ALTER USER

So for 8.0 connections it should run "ALTER USER 'username'@'%' WITH MAX_USER_CONNECTIONS 100"

**Comment by sibwy** [comment]
Thank you. This issue is reproducible with v13.1.8 and MySQL v8.0.23.

**Comment by sibwy** [comment]
Fixed in v13.1.9
