### ISSUE TITLE
ClickHouse MySQL interface

### ISSUE THREAD

**Issue by syco** [webyog/sqlyog-community#2288]
Hi,

clickhouse exposes a mysql interface on port 9004 and support basic sql syntax.

Unfortunately when I try to expand the tables list in the left column I get this error:
```txt
show full tables from `test_db` where table_type = 'BASE TABLE'

Error 62

Code: 62. DB::Exception: Syntax error: failed at position 6 ('full'): full tables from `test_db` where table_type = 'BASE TABLE'. Expected one of: CREATE, DATABASES, CLUSTERS, CLUSTER, CHANGED, SETTINGS, TABLES, DICTIONARIES, CREATE, PROCESSLIST, ACCESS, USERS, ROLES, SETTINGS PROFILES, PROFILES, ROW POLICIES, POLICIES, QUOTAS, CURRENT ROLES, ENABLED ROLES, CURRENT QUOTA, QUOTA, GRANTS, PRIVILEGES. (SYNTAX_ERROR) (version 22.2.1.3052)
```
is there a specificsql mode I should use to get it to work?
Thanks

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
