### ISSUE TITLE
mysql 8 service crashes when trying to backup

### ISSUE THREAD

**Issue by acordovar** [webyog/sqlyog-community#2293]
When I try to backup a database the mysql 8 service crashes.
I am using MySQL Yog GUI v13.1.9 (x64) and MySQL 8.0.28
Does anyone know why?

Thanks!

**Comment by sibwy** [comment]
Please contact us by email at ideramysqlsupport@idera.com about this. The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
