### ISSUE TITLE
Can it be adapted to the macOS version

### ISSUE THREAD

**Issue by fredeason** [webyog/sqlyog-community#2298]
Can sqlyog adapt to macos? I have tried various methods, but they are not perfect. I really want the macos version of sqlyog

sqlyog能适应macos吗？我尝试了各种方法，但它们并不完美。我真的想要sqlyog的macos版本

**Comment by sibwy** [comment]
We currently do not have plans to release a mac version. 

There is already an open request for the same here >> https://github.com/webyog/sqlyog-community/issues/2273
