### ISSUE TITLE
SSH connection fails with ed25519 keys

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2302]
On connecting to a server through SSH with Ed25519 encrypted private key, the connection fails with SQLyog. But, the connection works successfully with PuTTY 0.77.

The user report can be found in SF >> 00955083

**Comment by arif-rh** [comment]
Any update on this issue? I also got this issue using SQLyog Ultimate v13.1.9 (64bit)

**Comment by fritzmg** [comment]
I was in contact with support about this, they said they will try to fix it - however I haven't heard anything for a while now.

**Comment by sibwy** [comment]
Fixed in SQLyog [v13.2.0](https://webyog.com/blog/sqlyog/new-release-sqlyog-13-2-0/)
