### ISSUE TITLE
SSH Tunnel width "OpenSSL 1.1.1k  FIPS 25 Mar 2021" key does not work

### ISSUE THREAD

**Issue by mikehageman** [webyog/sqlyog-community#2308]
SQLYOG is not able to connect mariadb through a tunnel on servers with almalinux 8 and SSH Tunnel width OpenSSL 1.1.1k FIPS 25 Mar 2021. I compared the keys and the bigger keys do not work in sqlyog. It has something to do with plink version used. HeidiSQL and PUTTY work fine.

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
