### ISSUE TITLE
SQLYog still in business?  I don't think so.

### ISSUE THREAD

**Issue by lwoods** [webyog/sqlyog-community#2314]
I call SQLYog phone #.  It answers, and then hangs up.  I try to sign onto the forum...which I have signed onto in the past...and it says that I need a new password.  I enter my email (which I have an active account at SQLYog) and it says that it has sent me a link.  NOPE! I never receive a link.
SQLYog Product:  10 in my book.
SQLYog Support: ZERO!

BTW.  Why was I trying to contact SQLYog?  Oh.  Simply because I lost my list of connections and was down!

**Comment by sibwy** [comment]
Please contact us by email at ideramysqlsupport@idera.com about this and our Support team will help you.
