### ISSUE TITLE
Supporting newly added datatypes in MariaDB

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2328]
There have been a few dataypes newly added in MariaDB v10.x which need to be updated in SQLyog. Below are the details,

**INET4** (introduced in MariaDB 10.10.0)
**INET6** (introduced in MariaDB 10.5.0)
**UUID**  (introduced in MariaDB 10.7.0)

The user request can be found in SF >> 01011856

**Comment by kl3sk** [comment]
At least a way to "read" binary.

I'm using Ulid through Symfony/Doctrine2

Here what I see
![image](https://github.com/webyog/sqlyog-community/assets/2953145/89e2f1a7-bc8e-4cf5-86cc-2c1b5173136f)

**Comment by SendiMyrkr** [comment]
Something new about this? I would really appreciate this.

**Comment by sibwy** [comment]
This request is added in [SQLyog v13.3.0](https://webyog.com/blog/sqlyog/sqlyog-13-3-release-notes/).

**Comment by kl3sk** [comment]
Hello,

Does it available in the community edition too ? I can't see any changes inside.

By the way, your link is dead.
