### ISSUE TITLE
Support for newly added collations in MariaDB server

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2329]
With MariaDB v10.10 and above, new collations have been added to the character_set's. These newly added collations are not displayed in the drop-down in Create/Alter DB, Create/Alter table, etc.

The user report can be found in SF >> 01011736

**Comment by dlong500** [comment]
Can we get some traction on this?  It's frustrating to work with newer databases using modern collations when the app doesn't recognize them.  Given this applies not only to the community version but also to paid versions these types of issues really need to be given priority in the development process.

**Comment by sibwy** [comment]
This request is added in [SQLyog v13.3.0](https://webyog.com/blog/sqlyog/sqlyog-13-3-release-notes/).
