### ISSUE TITLE
What is the TLS version that is being used on Schedule and Reporting?

### ISSUE THREAD

**Issue by jrca025** [webyog/sqlyog-community#2331]
My concern is that I am using AWS SES for sending emails and they will depreciate TLSv1.1 below. And I am receiving notifs regarding my sqlyog not being TLSv1.2

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
