### ISSUE TITLE
Have SJA just dump the SQL file locally (not email)

### ISSUE THREAD

**Issue by hgpit** [webyog/sqlyog-community#2332]
Hello,

Am testing SQLyog Job Agent v13.2.0.

All we need is to be able to dump the resulting SQL output to file - not email email it out. This seems so simple, and one would have thought a natural stage in the email process, but we can't figure out how to do it.

Please can you advise how we can just get the output file please?

Thank you.

EJ

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue-tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
