### ISSUE TITLE
Unable to add/alter data with MariaDB v11.1 and above

### ISSUE THREAD

**Issue by sibwy** [webyog/sqlyog-community#2336]
With MariaDB v11.1 and above, it is impossible to add/edit the data in the 'Table Data'/'Result' tabs. An empty drop-down is displayed on clicking on the cells and closing the drop-down truncates already existing data in the respective cell.

Also, the string data isn't enclosed inside quotes when exporting the data using "Backup Table(s) As SQL Dump".

Use this sample SQL to reproducible: [MariaDB_11.1_issue.sql.zip](https://github.com/webyog/sqlyog-community/files/13497815/MariaDB_11.1_issue.sql.zip)

The user reports can be found in SF >> 01021644, 01023031, 01106693, 01113068, 01119298

**Comment by kl3sk** [comment]
I can confirm on `10.6.16`

**Comment by helders** [comment]
Looking forward to a fix to this issue too

**Comment by majuca** [comment]
is ok with the version SQLYog 13.3.0

**Comment by helders** [comment]
> majuca

I was using SQLYog version 13.1.6 and it was working fine, just updated to 13.3.0 and can confirm it seems to be fixed there.

**Comment by sibwy** [comment]
This is fixed in [SQLyog v13.3.0](https://webyog.com/blog/sqlyog/sqlyog-13-3-release-notes/).
