### ISSUE TITLE
Underline characters are not displayed

### ISSUE THREAD

**Issue by wxxiong6** [webyog/sqlyog-community#2339]
![image](https://github.com/webyog/sqlyog-community/assets/6983441/e436e8b6-0318-42d4-8ffb-3e579b310482)

Underline characters are not displayed。

system:
版本	Windows 11 专业版
版本	23H2
安装日期	‎2023/‎5/‎28
操作系统版本	22631.2861
体验	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
