### ISSUE TITLE
高分辨率下信息框里的字体太小了

### ISSUE THREAD

**Issue by zouliming** [webyog/sqlyog-community#2340]
![image](https://github.com/webyog/sqlyog-community/assets/363066/c1bc4b27-709b-4a34-837c-d69c32c5e50c)
在高分辨率显示下，信息一栏，format 采用html格式，查看内容，字体特别小，而且不支持设置或者自定义。
希望可以支持自定义，或者设置。

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
