### ISSUE TITLE
`Functional Index` not supported by Schema Synchronisation Tool in latest version v13.2.1

### ISSUE THREAD

**Issue by Cow258** [webyog/sqlyog-community#2341]
`Functional Index` not supported by Schema Synchronisation Tool in latest version v13.2.1
```sql
ALTER TABLE users ADD INDEX flags ((
  CAST(flags AS CHAR(255) array)
));
```
## Currently
![image](https://github.com/webyog/sqlyog-community/assets/14261588/1b6ec4d3-d5f1-4a23-9f75-ae67a7d8239b)

## Expected
```sql
ALTER TABLE `users` 
	ADD COLUMN `flags` json   NULL after `fromApp` , 
	ADD KEY `flags` ((cast(`flags` as char(255) array)));

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
