### ISSUE TITLE
Connection to mariadb 10.11.6 over ssh failure

### ISSUE THREAD

**Issue by syco** [webyog/sqlyog-community#2343]
Hi,

connecting to mariadb 10.11.6 over ssh fails with the following log message:
```txt
020c:fixme:secur32:GetUserNameExW NameFormat 8 not implemented
020c:fixme:secur32:GetUserNameExW NameFormat 8 not implemented
020c:fixme:crypt:CryptProtectMemory (00007FFFFEA007D0 16 00000001): stub
```
But it works as expected when connecting directly.

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
