### ISSUE TITLE
No email support?

### ISSUE THREAD

**Issue by mclaborn** [webyog/sqlyog-community#2344]
I've been trying for some time to get email support from email address ideramysqlsupport@idera.com and am not getting any response. Is that the correct email? 

Please reply to "Copy Tables/Database dialog problem [ ref:!00D300HwR.!500Vq033FnG:ref ]"

**Comment by sibwy** [comment]
Heard from the Support team that the ticket is active, the team is looking into it and will get back to you immediately.
