### ISSUE TITLE
table name completion is missing

### ISSUE THREAD

**Issue by chilipepper987** [webyog/sqlyog-community#2345]
When I type `SELECT FROM myDatabase.` I expect a list of tables to appear and to be narrowed down as a type. However, nothing appears. Pressing ctrl+space or ctrl+enter+space does nothing either. Is the autocomplete broken? Was it removed?

sqlyog community 13.2.1

**Comment by sibwy** [comment]
Please get in touch with us at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. We use GitHub strictly as an issue tracker for known issues and not for support or discussions. This is necessary to keep the system manageable.
