### ISSUE TITLE
Right-clicking a column when many rows are loaded, crashes/(temporarily?) freezes the application (very old bug)

### ISSUE THREAD

**Issue by hb-webdev** [webyog/sqlyog-community#2351]
After using a much older version of this program, along with the most recent Community release, if many, many, many rows are loaded, then right-clicking a column names freezes/crashes the application. Can we handle this more gracefully? Maybe throw a popup that says "If x number or more rows are loaded, right-click on column headers is disabled" or something? It's the only bad part of using this app. It sucks to constantly lose all my open tabs when I right-click a column header after forgetting that the app will crash on me if too many rows are loaded...

**Comment by sibwy** [comment]
Please contact us by email at [ideramysqlsupport@idera.com](mailto:ideramysqlsupport@idera.com) about this. The way we use GitHub is strictly as an issue tracker for known issues and not for support or discussions. This is necessary in order to keep the system manageable.
