### ISSUE TITLE
with many tables in a database Schema Designer will paint of top of objects already painted

### ISSUE THREAD

**Issue by atulwy** [webyog/sqlyog-community#917]
Original [issue 916](https://code.google.com/p/sqlyog/issues/detail?id=916) created by webyog on 2008-11-05T12:53:21.000Z:

It happens when there are too many tables.  Then we will start painting 
again from upper-left corner.  But we currently only utilize around 20-25% 
of canvas width, so we should utilize more of that width when it happens 
like this.  However it is a little complex in programming terms as we do 
not know the heigth of tables in advance.  But we could detect when 
repainting on top of existing tables is about to start and utilize the 
rightmost space of the canvas instead. Or we may let user decide how much 
width of canvas we should use.

**Comment by sibwy** [comment]
Another user has asked for this option to arrange the tables properly and not overlap on other tables.

The user request can be found in HS >> #92403

**Comment by sibwy** [comment]
This is fixed in SQLyog v13.1.0.
